name: deno-cd

on:
  workflow_call:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build against'
        required: true
        default: 'latest'
  push:
    branches:
      - dev
    tags: "*"

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ steps.app-token.outputs.token }}
      - name: Set Tag
        id: set-tag
        run: |
          if [[ -n "${{ github.event.inputs.tag }}" ]]; then
            echo "::set-output name=tag::${{ github.event.inputs.tag }}"
          elif [[ "${{ github.ref }}" =~ ^refs/tags/ ]]; then
            echo "::set-output name=tag::${GITHUB_REF#refs/tags/}"
          else
            echo "::set-output name=tag::latest"
          fi
      - name: Show Generated Tag
        run: |
          echo "Tag: ${{ steps.set-tag.outputs.tag }}"
      - name: Build and Push Docker Image
        run: |
          docker buildx create --use
          docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --cache-from type=registry,ref=ghcr.io/anitrend/on-the-edge:cache,mode=max \
          --cache-to type=registry,ref=ghcr.io/anitrend/on-the-edge:cache,mode=max \
          --tag ghcr.io/anitrend/on-the-edge:${{ steps.set-tag.outputs.tag }} \
          --push .
        working-directory: .
