name: deno-format

on:
  pull_request:
    types: [opened, synchronize]

permissions:
  contents: read

jobs:
  format:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v1
        id: app-token
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_SECRET }}
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ steps.app-token.outputs.token }}
          ref: ${{ github.head_ref }}
          # Make sure the value of GITHUB_TOKEN will not be persisted in repo's config
          persist-credentials: false

      - name: setup deno
        uses: denoland/setup-deno@v2

      - name: auto-format code
        run: deno fmt
        
      - name: check for file changes
        id: git_status
        run: |
          echo "::set-output name=status::$(git status -s)"

      - name: create pull request with formatting corrections
        if: ${{contains(steps.git_status.outputs.status, ' ')}}
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(automation): auto format code using deno fmt"
          commit_options: '--no-verify --signoff'
          file_pattern: '*.ts'
          repository: .
          
